---
title: "color_blind_tests"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{color_blind_tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

---
title: "Color Blind Tests"
output: rmarkdown::html_vignette
options: rmarkdown.html_vignette.check_title = FALSE
vignette: >
  %\VignetteIndexEntry{color_blind_tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Library

```{r}
library(colorBlindness)
library(dichromat)
library(cowplot)
library(colorblindr)
library(colorspace)
```

# Color-Blindness Tests

```{r}
# with white text
AAA_colors <- c("#012169", "#00539B", "#005587", "#262626")
AA_colors <- c("#C84E00", "#1D6363", "#0577B1", "#993399", "#666666")
AA18_colors <-  c("#339898", "#988675")

```

```{r}
knitr::knit_exit()
```

# colorBliness package

```{r, warning = FALSE}
values1 <- c("#00539B", "#339898", "#C84E00", "#A1B70D", "#E89923",
                       "#993399", "#012169", "#262626")
values2 <- c("#00539B", "#C84E00","#339898", "#A1B70D", "#993399", "#E89923",
                      "#012169", "#262626")
values3 <- c("#00539B", "#C84E00","#339898", "#A1B70D", "#993399", "#988675",
                      "#012169", "#262626")              
colorBlindness::displayAllColors(values1)
colorBlindness::displayAllColors(values2)
colorBlindness::displayAllColors(values3)
```
# Dichromat package

```{r}
# Option 1
pars <- par(mfrow=c(2,2), mar=c(0,0,2,0))
barplot(rep(1,8), yaxt="n", col=values1, main="True")
barplot(rep(1,8), yaxt="n", col=dichromat(values1, type="protan"), main="Protanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values1, type="deutan"), main="Deutanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values1, type="tritan"), main="Tritanopia")
```

```{r}
# Option 2
pars <- par(mfrow=c(2,2), mar=c(0,0,2,0))
barplot(rep(1,8), yaxt="n", col=values2, main="True")
barplot(rep(1,8), yaxt="n", col=dichromat(values2, type="protan"), main="Protanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values2, type="deutan"), main="Deutanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values2, type="tritan"), main="Tritanopia")
```

```{r}
# Option 3
pars <- par(mfrow=c(2,2), mar=c(0,0,2,0))
barplot(rep(1,8), yaxt="n", col=values3, main="True")
barplot(rep(1,8), yaxt="n", col=dichromat(values3, type="protan"), main="Protanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values3, type="deutan"), main="Deutanopia")
barplot(rep(1,8), yaxt="n", col=dichromat(values3, type="tritan"), main="Tritanopia")
```

# Colorblindr package

```{r}
# Dumby Dataset for Increased Categories
Student <- c("Jack", "Annie", "Paul", "Aidan", "Jake", "Josh", "Grace", "Suzy", "Beth", "Taylor", "Tanner", "Lisa", "Jimmy", "Larry", "Patricia", "Laura", "Yasmin", "Tim")
Grade <- c("A+", "B", "A+", "C", "D", "A+", "E", "C", "B-", "B-", "D", "A-", "B+", "A-", "A-", "D", "B", "E")

dumby_df <- data.frame(Student, Grade)
```


# Barplot

```{r, warning = FALSE}
bplot <- dumby_df %>%
  ggplot(aes(x = Grade, fill = Grade)) + 
  geom_bar() + 
  labs(title = "Grade Distribution") +
  theme_duke()


cvd_grid(bplot + scale_duke_fill_discrete(1))
```

```{r, warning = FALSE}
# Option 1
b2 <- edit_colors(bplot +
                    scale_duke_fill_discrete(num = 1), deutan, sev = 0.7)
cowplot::plot_grid(bplot +
                     scale_duke_fill_discrete(num = 1), b2)

# Option 2
b3 <- edit_colors(bplot +
                    scale_duke_fill_discrete(num = 2), deutan, sev = 0.7)
cowplot::plot_grid(bplot +
                     scale_duke_fill_discrete(num = 2), b3)

# Option 3
b4 <- edit_colors(bplot +
                    scale_duke_fill_discrete(num = 3), deutan, sev = 0.7)
cowplot::plot_grid(bplot +
                     scale_duke_fill_discrete(num = 3), b4)
```
# Scatterplot

```{r, message = FALSE}
splot <- ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, 
                              color = species)) +
  geom_point() +
  labs(title = "Flipper Length v. Depth") +
    theme_duke()

cvd_grid(splot)
```

```{r, warning = FALSE, message=FALSE}
# Option 1
s2 <- edit_colors(splot +
                    scale_duke_color_discrete(num = 1), deutan, sev = 0.7)
cowplot::plot_grid(splot +
                     scale_duke_color_discrete(num = 1), s2)

# Option 2
s3 <- edit_colors(splot +
                    scale_duke_color_discrete(num = 2), deutan, sev = 0.7)
cowplot::plot_grid(splot +
                    scale_duke_color_discrete(num = 2), s3)

# Option 3
s4 <- edit_colors(splot +
                    scale_duke_color_discrete(num = 3), deutan, sev = 0.7)
cowplot::plot_grid(splot +
                    scale_duke_color_discrete(num = 3), s4)
```

# References: 

https://www.datanovia.com/en/blog/how-to-stimulate-colorblindness-vision-in-r-figures/

http://australianantarcticdatacentre.github.io/GentleR/2015-07-23/dichromat.pdf

https://brand.duke.edu/colors/

https://ggplot2-book.org/scale-colour.html


